- name: configure backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create expense user #idempotenency will be taken care by ansible we do not need to worry
    ansible.builtin.user:
      name: expense

  - name: create app directory
    ansible.builtin.file: #we use this module to create directory but we need to mention explicitly as state: directory or else instead of directory file will be created
      path: /app
      state: directory 

  - name: download the backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: extract the backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip #by default ansible thinks this is in ansible server but this file is in remote server where ansible is connecting to
      dest: /
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install #before running this command ansible goes to /app dir and runs the command as npm install should run from location where we placed package.json
    args:
      chdir: /app 
      